// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agentmuxd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_STATUS_RUNNING Status = 1 // tmux session active, pane output changed recently
	Status_STATUS_IDLE    Status = 2 // tmux session active, no pane output for a while
	Status_STATUS_DEAD    Status = 3 // instance is configured but no tmux session found
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_RUNNING",
		2: "STATUS_IDLE",
		3: "STATUS_DEAD",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_RUNNING": 1,
		"STATUS_IDLE":    2,
		"STATUS_DEAD":    3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_agentmuxd_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_agentmuxd_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_UNKNOWN EventType = 0
	EventType_EVENT_UPDATED EventType = 1
	EventType_EVENT_REMOVED EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_UPDATED",
		2: "EVENT_REMOVED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNKNOWN": 0,
		"EVENT_UPDATED": 1,
		"EVENT_REMOVED": 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agentmuxd_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_agentmuxd_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{1}
}

type ControlAction int32

const (
	ControlAction_CONTROL_UNKNOWN ControlAction = 0
	ControlAction_CONTROL_START   ControlAction = 1
	ControlAction_CONTROL_STOP    ControlAction = 2
	ControlAction_CONTROL_RESTART ControlAction = 3
)

// Enum value maps for ControlAction.
var (
	ControlAction_name = map[int32]string{
		0: "CONTROL_UNKNOWN",
		1: "CONTROL_START",
		2: "CONTROL_STOP",
		3: "CONTROL_RESTART",
	}
	ControlAction_value = map[string]int32{
		"CONTROL_UNKNOWN": 0,
		"CONTROL_START":   1,
		"CONTROL_STOP":    2,
		"CONTROL_RESTART": 3,
	}
)

func (x ControlAction) Enum() *ControlAction {
	p := new(ControlAction)
	*p = x
	return p
}

func (x ControlAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlAction) Descriptor() protoreflect.EnumDescriptor {
	return file_agentmuxd_proto_enumTypes[2].Descriptor()
}

func (ControlAction) Type() protoreflect.EnumType {
	return &file_agentmuxd_proto_enumTypes[2]
}

func (x ControlAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlAction.Descriptor instead.
func (ControlAction) EnumDescriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{2}
}

type Instance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Agent            string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Provider         string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Workdir          string                 `protobuf:"bytes,5,opt,name=workdir,proto3" json:"workdir,omitempty"`
	TmuxSession      string                 `protobuf:"bytes,6,opt,name=tmux_session,json=tmuxSession,proto3" json:"tmux_session,omitempty"`
	Status           Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=agentmuxd.v1.Status" json:"status,omitempty"`
	Pid              int64                  `protobuf:"varint,8,opt,name=pid,proto3" json:"pid,omitempty"`
	LastActivityUnix int64                  `protobuf:"varint,9,opt,name=last_activity_unix,json=lastActivityUnix,proto3" json:"last_activity_unix,omitempty"`
	StartedAtUnix    int64                  `protobuf:"varint,10,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"` // 0 if the instance has no live tmux session
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_agentmuxd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Instance) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Instance) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Instance) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Instance) GetTmuxSession() string {
	if x != nil {
		return x.TmuxSession
	}
	return ""
}

func (x *Instance) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Instance) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Instance) GetLastActivityUnix() int64 {
	if x != nil {
		return x.LastActivityUnix
	}
	return 0
}

func (x *Instance) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

type ListInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_agentmuxd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{1}
}

type ListInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_agentmuxd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{2}
}

func (x *ListInstancesResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_agentmuxd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{3}
}

type InstanceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=agentmuxd.v1.EventType" json:"type,omitempty"`
	Instance      *Instance              `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceEvent) Reset() {
	*x = InstanceEvent{}
	mi := &file_agentmuxd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceEvent) ProtoMessage() {}

func (x *InstanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceEvent.ProtoReflect.Descriptor instead.
func (*InstanceEvent) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{4}
}

func (x *InstanceEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNKNOWN
}

func (x *InstanceEvent) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_agentmuxd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{5}
}

func (x *AttachRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_agentmuxd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{6}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Attach
	//	*ClientMessage_Stdin
	//	*ClientMessage_Resize
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_agentmuxd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{7}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetAttach() *AttachRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ClientMessage) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ClientMessage) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Attach struct {
	Attach *AttachRequest `protobuf:"bytes,1,opt,name=attach,proto3,oneof"` // must be the first message on the stream
}

type ClientMessage_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ClientMessage_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ClientMessage_Attach) isClientMessage_Payload() {}

func (*ClientMessage_Stdin) isClientMessage_Payload() {}

func (*ClientMessage_Resize) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Stdout
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agentmuxd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ServerMessage) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Stdout) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Action        ControlAction          `protobuf:"varint,2,opt,name=action,proto3,enum=agentmuxd.v1.ControlAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_agentmuxd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{9}
}

func (x *ControlRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ControlRequest) GetAction() ControlAction {
	if x != nil {
		return x.Action
	}
	return ControlAction_CONTROL_UNKNOWN
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_agentmuxd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentmuxd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_agentmuxd_proto_rawDescGZIP(), []int{10}
}

func (x *ControlResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agentmuxd_proto protoreflect.FileDescriptor

const file_agentmuxd_proto_rawDesc = "" +
	"\n" +
	"\x0fagentmuxd.proto\x12\fagentmuxd.v1\"\xb9\x02\n" +
	"\bInstance\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x18\n" +
	"\aworkdir\x18\x05 \x01(\tR\aworkdir\x12!\n" +
	"\ftmux_session\x18\x06 \x01(\tR\vtmuxSession\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.agentmuxd.v1.StatusR\x06status\x12\x10\n" +
	"\x03pid\x18\b \x01(\x03R\x03pid\x12,\n" +
	"\x12last_activity_unix\x18\t \x01(\x03R\x10lastActivityUnix\x12&\n" +
	"\x0fstarted_at_unix\x18\n" +
	" \x01(\x03R\rstartedAtUnix\"\x16\n" +
	"\x14ListInstancesRequest\"M\n" +
	"\x15ListInstancesResponse\x124\n" +
	"\tinstances\x18\x01 \x03(\v2\x16.agentmuxd.v1.InstanceR\tinstances\"\x15\n" +
	"\x13StreamEventsRequest\"p\n" +
	"\rInstanceEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.agentmuxd.v1.EventTypeR\x04type\x122\n" +
	"\binstance\x18\x02 \x01(\v2\x16.agentmuxd.v1.InstanceR\binstance\"+\n" +
	"\rAttachRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x99\x01\n" +
	"\rClientMessage\x125\n" +
	"\x06attach\x18\x01 \x01(\v2\x1b.agentmuxd.v1.AttachRequestH\x00R\x06attach\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12.\n" +
	"\x06resize\x18\x03 \x01(\v2\x14.agentmuxd.v1.ResizeH\x00R\x06resizeB\t\n" +
	"\apayload\"L\n" +
	"\rServerMessage\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"a\n" +
	"\x0eControlRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x123\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1b.agentmuxd.v1.ControlActionR\x06action\";\n" +
	"\x0fControlResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*R\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x01\x12\x0f\n" +
	"\vSTATUS_IDLE\x10\x02\x12\x0f\n" +
	"\vSTATUS_DEAD\x10\x03*D\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x11\n" +
	"\rEVENT_UPDATED\x10\x01\x12\x11\n" +
	"\rEVENT_REMOVED\x10\x02*^\n" +
	"\rControlAction\x12\x13\n" +
	"\x0fCONTROL_UNKNOWN\x10\x00\x12\x11\n" +
	"\rCONTROL_START\x10\x01\x12\x10\n" +
	"\fCONTROL_STOP\x10\x02\x12\x13\n" +
	"\x0fCONTROL_RESTART\x10\x032\xcc\x02\n" +
	"\x0eAgentmuxDaemon\x12X\n" +
	"\rListInstances\x12\".agentmuxd.v1.ListInstancesRequest\x1a#.agentmuxd.v1.ListInstancesResponse\x12P\n" +
	"\fStreamEvents\x12!.agentmuxd.v1.StreamEventsRequest\x1a\x1b.agentmuxd.v1.InstanceEvent0\x01\x12F\n" +
	"\x06Attach\x12\x1b.agentmuxd.v1.ClientMessage\x1a\x1b.agentmuxd.v1.ServerMessage(\x010\x01\x12F\n" +
	"\aControl\x12\x1c.agentmuxd.v1.ControlRequest\x1a\x1d.agentmuxd.v1.ControlResponseB-Z+github.com/m-rk/agentmux/daemon/internal/pbb\x06proto3"

var (
	file_agentmuxd_proto_rawDescOnce sync.Once
	file_agentmuxd_proto_rawDescData []byte
)

func file_agentmuxd_proto_rawDescGZIP() []byte {
	file_agentmuxd_proto_rawDescOnce.Do(func() {
		file_agentmuxd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentmuxd_proto_rawDesc), len(file_agentmuxd_proto_rawDesc)))
	})
	return file_agentmuxd_proto_rawDescData
}

var file_agentmuxd_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agentmuxd_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agentmuxd_proto_goTypes = []any{
	(Status)(0),                   // 0: agentmuxd.v1.Status
	(EventType)(0),                // 1: agentmuxd.v1.EventType
	(ControlAction)(0),            // 2: agentmuxd.v1.ControlAction
	(*Instance)(nil),              // 3: agentmuxd.v1.Instance
	(*ListInstancesRequest)(nil),  // 4: agentmuxd.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil), // 5: agentmuxd.v1.ListInstancesResponse
	(*StreamEventsRequest)(nil),   // 6: agentmuxd.v1.StreamEventsRequest
	(*InstanceEvent)(nil),         // 7: agentmuxd.v1.InstanceEvent
	(*AttachRequest)(nil),         // 8: agentmuxd.v1.AttachRequest
	(*Resize)(nil),                // 9: agentmuxd.v1.Resize
	(*ClientMessage)(nil),         // 10: agentmuxd.v1.ClientMessage
	(*ServerMessage)(nil),         // 11: agentmuxd.v1.ServerMessage
	(*ControlRequest)(nil),        // 12: agentmuxd.v1.ControlRequest
	(*ControlResponse)(nil),       // 13: agentmuxd.v1.ControlResponse
}
var file_agentmuxd_proto_depIdxs = []int32{
	0,  // 0: agentmuxd.v1.Instance.status:type_name -> agentmuxd.v1.Status
	3,  // 1: agentmuxd.v1.ListInstancesResponse.instances:type_name -> agentmuxd.v1.Instance
	1,  // 2: agentmuxd.v1.InstanceEvent.type:type_name -> agentmuxd.v1.EventType
	3,  // 3: agentmuxd.v1.InstanceEvent.instance:type_name -> agentmuxd.v1.Instance
	8,  // 4: agentmuxd.v1.ClientMessage.attach:type_name -> agentmuxd.v1.AttachRequest
	9,  // 5: agentmuxd.v1.ClientMessage.resize:type_name -> agentmuxd.v1.Resize
	2,  // 6: agentmuxd.v1.ControlRequest.action:type_name -> agentmuxd.v1.ControlAction
	4,  // 7: agentmuxd.v1.AgentmuxDaemon.ListInstances:input_type -> agentmuxd.v1.ListInstancesRequest
	6,  // 8: agentmuxd.v1.AgentmuxDaemon.StreamEvents:input_type -> agentmuxd.v1.StreamEventsRequest
	10, // 9: agentmuxd.v1.AgentmuxDaemon.Attach:input_type -> agentmuxd.v1.ClientMessage
	12, // 10: agentmuxd.v1.AgentmuxDaemon.Control:input_type -> agentmuxd.v1.ControlRequest
	5,  // 11: agentmuxd.v1.AgentmuxDaemon.ListInstances:output_type -> agentmuxd.v1.ListInstancesResponse
	7,  // 12: agentmuxd.v1.AgentmuxDaemon.StreamEvents:output_type -> agentmuxd.v1.InstanceEvent
	11, // 13: agentmuxd.v1.AgentmuxDaemon.Attach:output_type -> agentmuxd.v1.ServerMessage
	13, // 14: agentmuxd.v1.AgentmuxDaemon.Control:output_type -> agentmuxd.v1.ControlResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agentmuxd_proto_init() }
func file_agentmuxd_proto_init() {
	if File_agentmuxd_proto != nil {
		return
	}
	file_agentmuxd_proto_msgTypes[7].OneofWrappers = []any{
		(*ClientMessage_Attach)(nil),
		(*ClientMessage_Stdin)(nil),
		(*ClientMessage_Resize)(nil),
	}
	file_agentmuxd_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMessage_Stdout)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentmuxd_proto_rawDesc), len(file_agentmuxd_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentmuxd_proto_goTypes,
		DependencyIndexes: file_agentmuxd_proto_depIdxs,
		EnumInfos:         file_agentmuxd_proto_enumTypes,
		MessageInfos:      file_agentmuxd_proto_msgTypes,
	}.Build()
	File_agentmuxd_proto = out.File
	file_agentmuxd_proto_goTypes = nil
	file_agentmuxd_proto_depIdxs = nil
}
