// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: agentmuxd.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentmuxDaemon_ListInstances_FullMethodName         = "/agentmuxd.v1.AgentmuxDaemon/ListInstances"
	AgentmuxDaemon_StreamEvents_FullMethodName          = "/agentmuxd.v1.AgentmuxDaemon/StreamEvents"
	AgentmuxDaemon_Attach_FullMethodName                = "/agentmuxd.v1.AgentmuxDaemon/Attach"
	AgentmuxDaemon_Control_FullMethodName               = "/agentmuxd.v1.AgentmuxDaemon/Control"
	AgentmuxDaemon_CreateInstance_FullMethodName        = "/agentmuxd.v1.AgentmuxDaemon/CreateInstance"
	AgentmuxDaemon_ListResumableSessions_FullMethodName = "/agentmuxd.v1.AgentmuxDaemon/ListResumableSessions"
)

// AgentmuxDaemonClient is the client API for AgentmuxDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentmuxDaemonClient interface {
	// Snapshot of every instance the daemon currently knows about.
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// Pushes an event whenever an instance's status changes, so clients don't
	// need to poll ListInstances.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error)
	// Bidirectional PTY stream. The first client message must be an
	// AttachRequest naming the instance; every message after that is stdin
	// bytes or a resize. Server messages are stdout bytes or an error.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// Start/stop/restart an instance's systemd unit (Linux) or LaunchAgent
	// (macOS).
	Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// Provisions a brand new instance on this host: writes its registry
	// entry, installs its unit/LaunchAgent, and starts it.
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	// Lists Claude Code session IDs resumable for a given workdir, for the
	// wizard's resume picker.
	ListResumableSessions(ctx context.Context, in *ListResumableSessionsRequest, opts ...grpc.CallOption) (*ListResumableSessionsResponse, error)
}

type agentmuxDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentmuxDaemonClient(cc grpc.ClientConnInterface) AgentmuxDaemonClient {
	return &agentmuxDaemonClient{cc}
}

func (c *agentmuxDaemonClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, AgentmuxDaemon_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentmuxDaemonClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentmuxDaemon_ServiceDesc.Streams[0], AgentmuxDaemon_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, InstanceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentmuxDaemon_StreamEventsClient = grpc.ServerStreamingClient[InstanceEvent]

func (c *agentmuxDaemonClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentmuxDaemon_ServiceDesc.Streams[1], AgentmuxDaemon_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentmuxDaemon_AttachClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *agentmuxDaemonClient) Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, AgentmuxDaemon_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentmuxDaemonClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, AgentmuxDaemon_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentmuxDaemonClient) ListResumableSessions(ctx context.Context, in *ListResumableSessionsRequest, opts ...grpc.CallOption) (*ListResumableSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResumableSessionsResponse)
	err := c.cc.Invoke(ctx, AgentmuxDaemon_ListResumableSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentmuxDaemonServer is the server API for AgentmuxDaemon service.
// All implementations must embed UnimplementedAgentmuxDaemonServer
// for forward compatibility.
type AgentmuxDaemonServer interface {
	// Snapshot of every instance the daemon currently knows about.
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// Pushes an event whenever an instance's status changes, so clients don't
	// need to poll ListInstances.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[InstanceEvent]) error
	// Bidirectional PTY stream. The first client message must be an
	// AttachRequest naming the instance; every message after that is stdin
	// bytes or a resize. Server messages are stdout bytes or an error.
	Attach(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// Start/stop/restart an instance's systemd unit (Linux) or LaunchAgent
	// (macOS).
	Control(context.Context, *ControlRequest) (*ControlResponse, error)
	// Provisions a brand new instance on this host: writes its registry
	// entry, installs its unit/LaunchAgent, and starts it.
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// Lists Claude Code session IDs resumable for a given workdir, for the
	// wizard's resume picker.
	ListResumableSessions(context.Context, *ListResumableSessionsRequest) (*ListResumableSessionsResponse, error)
	mustEmbedUnimplementedAgentmuxDaemonServer()
}

// UnimplementedAgentmuxDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentmuxDaemonServer struct{}

func (UnimplementedAgentmuxDaemonServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedAgentmuxDaemonServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[InstanceEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAgentmuxDaemonServer) Attach(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedAgentmuxDaemonServer) Control(context.Context, *ControlRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedAgentmuxDaemonServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedAgentmuxDaemonServer) ListResumableSessions(context.Context, *ListResumableSessionsRequest) (*ListResumableSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResumableSessions not implemented")
}
func (UnimplementedAgentmuxDaemonServer) mustEmbedUnimplementedAgentmuxDaemonServer() {}
func (UnimplementedAgentmuxDaemonServer) testEmbeddedByValue()                        {}

// UnsafeAgentmuxDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentmuxDaemonServer will
// result in compilation errors.
type UnsafeAgentmuxDaemonServer interface {
	mustEmbedUnimplementedAgentmuxDaemonServer()
}

func RegisterAgentmuxDaemonServer(s grpc.ServiceRegistrar, srv AgentmuxDaemonServer) {
	// If the following call panics, it indicates UnimplementedAgentmuxDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentmuxDaemon_ServiceDesc, srv)
}

func _AgentmuxDaemon_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentmuxDaemonServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentmuxDaemon_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentmuxDaemonServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentmuxDaemon_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentmuxDaemonServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, InstanceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentmuxDaemon_StreamEventsServer = grpc.ServerStreamingServer[InstanceEvent]

func _AgentmuxDaemon_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentmuxDaemonServer).Attach(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentmuxDaemon_AttachServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _AgentmuxDaemon_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentmuxDaemonServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentmuxDaemon_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentmuxDaemonServer).Control(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentmuxDaemon_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentmuxDaemonServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentmuxDaemon_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentmuxDaemonServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentmuxDaemon_ListResumableSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResumableSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentmuxDaemonServer).ListResumableSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentmuxDaemon_ListResumableSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentmuxDaemonServer).ListResumableSessions(ctx, req.(*ListResumableSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentmuxDaemon_ServiceDesc is the grpc.ServiceDesc for AgentmuxDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentmuxDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentmuxd.v1.AgentmuxDaemon",
	HandlerType: (*AgentmuxDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstances",
			Handler:    _AgentmuxDaemon_ListInstances_Handler,
		},
		{
			MethodName: "Control",
			Handler:    _AgentmuxDaemon_Control_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _AgentmuxDaemon_CreateInstance_Handler,
		},
		{
			MethodName: "ListResumableSessions",
			Handler:    _AgentmuxDaemon_ListResumableSessions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _AgentmuxDaemon_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Attach",
			Handler:       _AgentmuxDaemon_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentmuxd.proto",
}
